// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { existsSync } from "node:fs";

// The docs pages are generated by scripts/import-docs.mjs from the versioncam
// package as npm publishes it; the sidebar groups the directories it writes.
// `more/` holds README sections the importer has no place for yet, and only
// appears when there are some.
const more = existsSync(new URL("./src/content/docs/more", import.meta.url));

// Code in the viewfinder's greys. Syntax colours would bring red and amber,
// which the brand keeps for recording and for numbers you can trust.
const viewfinder = {
  name: "viewfinder",
  type: "dark",
  colors: {
    "editor.background": "#0B0C0E",
    "editor.foreground": "#E6E8EB",
    "editor.selectionBackground": "#2A2E35",
    "terminal.background": "#0B0C0E",
    "terminal.foreground": "#E6E8EB",
  },
  tokenColors: [
    { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: "#8A8F98" } },
    { scope: ["string", "constant", "markup.inline.raw"], settings: { foreground: "#C9CCD1" } },
    {
      scope: ["keyword", "storage", "entity.name", "support.function", "entity.name.function"],
      settings: { foreground: "#FFFFFF" },
    },
    { scope: ["variable", "punctuation", "meta"], settings: { foreground: "#E6E8EB" } },
  ],
};

const OG = "https://version.cam/og-image.png";

export default defineConfig({
  site: "https://version.cam",
  integrations: [
    starlight({
      title: "Versioncam",
      description:
        "Record demo clips of a real web app: scripted, deterministic, re-recorded on every push.",
      logo: {
        src: "./src/assets/lockup-dark-bg.svg",
        alt: "Versioncam",
        replacesTitle: true,
      },
      favicon: "/favicon.svg",
      head: [
        { tag: "link", attrs: { rel: "icon", href: "/favicon.ico", sizes: "32x32" } },
        { tag: "link", attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" } },
        { tag: "meta", attrs: { name: "theme-color", content: "#000000" } },
        { tag: "meta", attrs: { property: "og:image", content: OG } },
        { tag: "meta", attrs: { property: "og:image:width", content: "1200" } },
        { tag: "meta", attrs: { property: "og:image:height", content: "630" } },
        {
          tag: "meta",
          attrs: { property: "og:image:alt", content: "version.cam: Your app, recorded from main." },
        },
        { tag: "meta", attrs: { name: "twitter:card", content: "summary_large_image" } },
        { tag: "meta", attrs: { name: "twitter:image", content: OG } },
        // The two faces every page sets its headings and body in.
        ...["DepartureMono-Regular", "Inter-Regular"].map((font) => ({
          tag: "link",
          attrs: {
            rel: "preload",
            href: `/fonts/${font}.woff`,
            as: "font",
            type: "font/woff",
            crossorigin: "",
          },
        })),
      ],
      components: {
        Hero: "./src/components/Hero.astro",
        ThemeProvider: "./src/components/DarkOnly.astro",
        ThemeSelect: "./src/components/NoThemeSelect.astro",
      },
      expressiveCode: {
        themes: [viewfinder],
        styleOverrides: {
          borderColor: "#2A2E35",
          borderRadius: "0",
          codeFontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
          codeFontSize: "0.875rem",
          codeLineHeight: "1.6",
          frames: {
            editorActiveTabIndicatorTopColor: "#FFFFFF",
            terminalTitlebarBackground: "#000000",
            terminalTitlebarBorderBottomColor: "#2A2E35",
            // The terminal is named in the on-screen voice (site.css), not
            // drawn as a macOS window.
            terminalTitlebarDotsOpacity: "0",
            frameBoxShadowCssValue: "none",
          },
        },
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/versioncam/versioncam-home",
        },
      ],
      customCss: ["./src/styles/site.css"],
      // Groups stay shut unless they hold the page being read (Starlight opens
      // that one itself): a handful of choices instead of fifteen links.
      sidebar: [
        { label: "Start", collapsed: true, items: [{ autogenerate: { directory: "start" } }] },
        {
          label: "Reference",
          collapsed: true,
          items: [{ autogenerate: { directory: "reference" } }],
        },
        {
          label: "How it works",
          collapsed: true,
          items: [{ autogenerate: { directory: "how-it-works" } }],
        },
        ...(more
          ? [{ label: "More", items: [{ autogenerate: { directory: "more" } }] }]
          : []),
        { label: "About", collapsed: true, items: [{ autogenerate: { directory: "about" } }] },
      ],
    }),
  ],
});
